### ISSUE TITLE
Added new FCORR Ratios

### ISSUE THREAD

**Issue by sparkji** [earthchem/EarthChemODM2TemplateReader#23]
@jasonash , please help adding new FCORR Ratios:
FCORR_Ratios: S34_S32
standard: ANDERSON PYRRHOTITE
value: 0.0450615
ref:2146

**Comment by jasonash** [comment]
@sparkji I have added the FCORR ratio above per your request. I hope this helps.

**Comment by sparkji** [comment]
@jasonash ,still not work, please take a look.
![image](https://user-images.githubusercontent.com/8258431/68511055-0b11c600-0243-11ea-8743-ed800793a634.png)

**Comment by jasonash** [comment]
OK, it should be fixed now. Please try again.

**Comment by sparkji** [comment]
confirm fixed
